# Linear Algebra Basics

Reference: https://cs229.stanford.edu/lectures-spring2022/cs229-linear_algebra_review.pdf

In [4]:
import numpy as np 
from numpy import array

from datetime import datetime
from pytz import timezone    

HK= timezone('Hongkong')
now = datetime.now(HK)
print("Current Time =", now)

Current Time = 2022-05-28 13:59:10.581675+08:00


# 1. Basic Concepts and Notation

![link text](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgtRQrgti0AtEpZ-QU8nPVwt86QIeKrupfln5_agT-i27DLJa9pLJFQaRPBUPAqaB2IK0&usqp=CAU)

In [18]:
from numpy import linalg as LA
# create a vector
a=array([1,-2,3])

# Magnitude of Vector 
len_a=LA.norm(x=a)
print(len_a)

# L1 norm of vector
L1_norm_a=LA.norm(x=a,ord=1)
print(L1_norm_a)

3.7416573867739413
6.0


# 2. Matrix Multiplication

## 2.1 Vector-Vector Products

In [6]:
# Dot Products

# define first vector
a = array([1, 2, 3])
# define second vector
b = array([5, 7, 8])
# multiply vectors
c = a.dot(b)
print(c)

43


In [17]:
# Cross Products
c = np.cross(a,b)
print(c)

# check if c is orthogonal to (a,b)
c_a=c.dot(a)
c_b=c.dot(b)
print(c_a,c_b)

[-37   7  17]
0 0


## 2.2 Matrix - Vector Products

In [29]:
# create a Matrix = A (3 * 3)
A = array([[1,2,5],
          [3,4,7],
          [5,6,8]])

# create a vector = x (3 * 1)
x=np.transpose(array([[0.2,0.3,0.6]]))
print(x)

# multiply
Ax=np.matmul(A,x)
Ax

[[0.2]
 [0.3]
 [0.6]]


array([[3.8],
       [6. ],
       [7.6]])

## 2.3 Matrix - Matrix Products

In [32]:
# create a Matrix = A (3 * 3)
A = array([[1,2,5],
          [3,4,7],
          [5,6,8]])
# create a Matrix = B (3 * 3)
B = array([[0,3,8],
          [7,9,5],
          [2,6,4]])

# multiply (C=AB)
AB=np.matmul(A,B)
AB


array([[ 24,  51,  38],
       [ 42,  87,  72],
       [ 58, 117, 102]])

# 3. Operations and Properties

## 3.1 The Identity Matrix and Diagonal Matrices


In [34]:
# The Identity Matrix
# https://numpy.org/doc/stable/reference/generated/numpy.identity.html
identity_4d=np.identity(n=4)
print(identity_4d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
# The Diagonal Matrix
# https://numpy.org/doc/stable/reference/generated/numpy.diag.html

# construct a 3*3 matrix
x = np.arange(9).reshape((3,3))
print(x)
# extract the diagonal element
diag_x_elements=np.diag(x)
print(diag_x_elements)
# construct diagonal matrix based on x
diag_x=np.diag(diag_x_elements)
print(diag_x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[[0 0 0]
 [0 4 0]
 [0 0 8]]


## 3.2 The Transpose
![link text](https://publish-01.obsidian.md/access/7117ab8e7aa458ff96feb9b07ca43319/Artificial%20Intelligence/625.252%20Linear%20Algebra/week5/children/matrix%20algebra%20theorem%203.png)

In [37]:
# construct a 4*3 matrix
x = np.arange(12).reshape((4,3))
print(x)
# calculate transpose
x_t=x.T
print(x_t)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


## 3.3 Symmetric Matrices

In [38]:
# A square matrix A ∈ R n×n is symmetric if A = AT
A=array([[1,0],
         [0,1]])
# check if A is symmetric
A==A.T

array([[ True,  True],
       [ True,  True]])

## 3.4 The Trace

![link text](https://www.tutorialexample.com/wp-content/uploads/2019/07/matrix-trace-example.png)
![link text](https://www.tau.ac.il/~tsirel/dump/Static/knowino.org/w/images/math/8/c/7/8c7ef7d26312dfaf7f699cd76992d0f9.png)

In [40]:
# matrix trace
from numpy import trace
# define matrix
A = array([
[5, 2, 3],
[4, -1, 6],
[7, 8, 7]])
# calculate trace
tr_A = trace(A)
print(tr_A)


11


## 3.5 Norm --- for vector

* Usually in ML, the vector = weights


* Definition: A measure of the “length” of the vector. For example, we have the commonly-used Euclidean or L2 norm = X_t * X

* Properties
![link text](https://www.tutorialexample.com/wp-content/uploads/2019/10/the-properties-of-matrix-norms.png)

In [43]:
# vector L1 norm = sum of abs of elements
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = LA.norm(a, 1)
print(l1)


[1 2 3]
6.0


In [44]:
# vector L2 norm --- Euclidean norm
# define vector
# calculate norm
l2 = LA.norm(a)
print(l2)


3.7416573867739413


## 3.6 Linear Independence and Rank



*   Col Space for Matrix = Space Spanned by Matrix Cols
*   Rank = Num of Dim in Col Space
*  Full Rank 
  * For A ∈ R m×n, rank(A) ≤ min(m, n). If rank(A) = min(m, n), then A is said to be full rank
  * Full Rank ==  each of the rows of the matrix are linearly independent
  * properties
    * rank(A) = rank(AT)
    * rank(AB) ≤ min(rank(A),rank(B))
    * rank(A + B) ≤ rank(A) + rank(B)




In [46]:
# matrix rank
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)

# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)

# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2


## 3.7 The Inverse of a Square Matrix

* only for n*n matrix
* Requirement for Invertiable:
  * A must be full rank (Det(A) not 0)
* A−1A = I = AA−1
* • (AB)−1 = B−1A−1
* • (A−1)T = (AT)−1
. For this reason this matrix is often denoted A−T


In [47]:
# invert matrix
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)


[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## 3.8 Orthogonal Matrices



*   Orthonormal Matrix
  * All the vectors orthogonal to each other (v_i * v_j = 0)
  * length of each vector = 1
  * U_T * U = I = U * U_T
*   Good Property of Orthonormal Matrix
  * U-1=U_T (inverse == transpose)
  * It preserve Vectors
      * angle
      * length
* G-S process to transform matrix to Orthonormal Matrix (QR Decomposition)
  * A = Q * R (Q=orthonormal matrix; R = upper tri matrix)




In [53]:
# Example of QR Decomposition
A = array([
[1.0, 2.0],
[3.0, 4.0],
[5,6]])
print(A)
q, r = LA.qr(A)
print(q)
print(r)
# reconstruct
A = q.dot(r)
print(A)


[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


## 3.9 Range and Nullspace of a Matrix

* Range == Col Space (Span of Matrix Vectors)
* Rank = num of dimension of Col Space(Range)
* Null Space:
   * for Matrix A: A*x=0
   * the set of vector x = Null Space (Kernel) of A


In [55]:
from scipy.linalg import null_space
A = np.array([[1, 1], [1, 1]])
ns=null_space(A)
ns

array([[-0.70710678],
       [ 0.70710678]])

## 3.10 The Determinant

* only for square n*n matrix
* intuition = the scale factor for specific transformation (Matrix A)
* Det = Scaler
  * if Det == 0, Dimension Reduced (rank reduced), No Invertiable
* Properties of Det
![link text](https://media.nagwa.com/478137856541/en/thumbnail_l.jpeg)


In [60]:
# matrix determinant
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[9, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
det_A = det(A)
print(det_A)


[[1 2 3]
 [9 5 6]
 [7 8 9]]
30.000000000000014


## 3.11 Quadratic Forms and Positive Semidefinite Matrices 

Skip, Dont get the point

## 3.12 Eigenvalues and Eigenvectors


*  Background
  * 'eigen' == own in german
  * eigen vector = after a linear transformation(A), the diretion invarient (only scaled)
  * eigen value = the scale factor
*   Example: for 3D Rotation (A), the eigen vector = Roataion Axis
* Notation
  * for Matrix A: A*x = lambda * x
  * x = eigen vector
  * lambda = eigen value
* Eigen Basis (Q) & Eigen Decomposition
  ![link text](https://www.sharetechnote.com/image/EngMath_Matrix_EigenDecomposition_02.png)
  * for A, the set of eigen vectors = Q
  * Motivation: Simplify (Diagonalize A)
    * beacuse, eigen basis (Q) only scaled (lambda) by Transformation A
    * A * Q = Q * lambda 
    * lambda = diag (lambda_1, ..., lambda_n)
    * A = Q * lambda * Q-1
  * Example
    * for q = AAA   
    * SO:
    * q = Q * lambda^3 * Q-1
      * if Q = Orthonormal Eigen Basis
        * q = Q * lambda^3 * Q_T 
* Properties
  * • The trace of a A is equal to the sum of its eigenvalues,
    * trA = sum (Lambda)
  * • The determinant of A is equal to the product of its eigenvalues
    * det (A) = Product (Lambda)
  * • The rank of A is equal to the number of non-zero eigenvalues of A.
  * • The eigenvalues of a diagonal matrix:
    * D = diag(d1, . . . dn) are just the diagonal entries d1, . . . dn.




In [62]:
# eigendecomposition
from numpy.linalg import eig
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [76]:
# test eigen vectors
e_g_1=vectors[:,0].reshape(3,1)
print(e_g_1)
transformed_e_g_1=np.matmul(A,e_g_1)
print(transformed_e_g_1)
# scaled by
transformed_e_g_1/e_g_1

[[-0.23197069]
 [-0.52532209]
 [-0.8186735 ]]
[[ -3.73863537]
 [ -8.46653421]
 [-13.19443305]]


array([[16.11684397],
       [16.11684397],
       [16.11684397]])

In [88]:
# Use Eigen Decompoisiton to simplify the computation
values, vectors = eig(A)
AAA= A@A@A
print(AAA)
# The Eigen Decomp Approach
# AAA = Q * diag_lambda ^3 * Q-1
diag_lambda=np.diag(values)
Q=vectors
Q_inv=inv(Q)
AAA_simple=Q@diag_lambda@diag_lambda@diag_lambda@Q_inv
print(AAA_simple)

[[ 468  576  684]
 [1062 1305 1548]
 [1656 2034 2412]]
[[ 468.  576.  684.]
 [1062. 1305. 1548.]
 [1656. 2034. 2412.]]
